### ISSUE TITLE
Change the face for : in keywords

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clojure-mode#343]
We talked about this on gitter a while back, but the more I think of this the more I'm convinced we shouldn't put a face on this token. Much like the `/` in namespaced stuff.  The `:` isn't really part of the keyword, but a token for the reader.  

```clj
user=> (name :foo)
;;=> "foo"
```

If the return value here was `":foo"`, then that would mean that the `:` was really part of the keyword, but since it isn't, I think we should drop the keyword face here.

**Comment by Malabarba** [comment]
I disagree for the following reason. `'` is a token for the reader, it can be used before anything and (most importantly) it can be followed by whitespace. That's what tells me that the quote is not part of the symbol. Also `'hi` evaluates to `hi`, because (again) the symbol is `hi`, and `'` is just shorthand for the quote special form. 

OTOH: `:hi` evaluates to `:hi`. There can be no whitespace after the `:` (it throws invalid token exception). And the `:` can't be used to "keywordize" anything else. 

Those all say to me that `:` is not just a token to the reader. It is part of a built-in type called keyword. Just like `"` is part of the string. 
To take that analogy a little further, the contents of the string `"hi"` is `hi` (similar to how the name of the keyword `:hi` is `hi`) but we still font-lock the double quote. :-)

**Comment by bbatsov** [comment]
I agree with Artur. Plus emacs-lisp-mode behaves like clojure-mode.

**Comment by expez** [comment]
> It is part of a built-in type called keyword. Just like `"` is part of the string. 

This doesn't really hold for `::`, though.  `::` really is, imo, very much like a token to the reader which means "expand this keyword to include the current namespace".

In common lisp, and in elisp, we have this behavior:

```el
(keywordp (intern ":foo"))
;; => t
(symbolp (intern ":foo"))
;; => t
```

Where symbols and keywords really are the same thing.  The difference being that keywords start with `:` and are always interned in the keyword package, whereas symbols are interned in the current package (in CL).

Given that, `:` and `'` are tokens to the reader, hinting about which symbol table should be used. But! Clearly, the `:` here is also part of the name of the symbol, because the only thing making this a keyword, in addition to being a symbol, is the leading `:`.  This is even clear in the [keywordp definition](https://github.com/emacs-mirror/emacs/blob/63cfb75f3a9d0f658e099ae18779e305a7e49fee/src/data.c#L327).

Clojure went in a slightly different direction and has implemented keywords and symbols as different types, where the keyword is much more lightweight (e.g. no support for metadata).  But, as you can see in the definition, [here](https://github.com/clojure/clojure/blob/clojure-1.7.0/src%2Fjvm%2Fclojure%2Flang%2FKeyword.java#L54), a keyword is a symbol in the keyword table in clojure too.  The `:` isn't even stored (unlike in say elisp above), it's just the way keywords print, and syntactic sugar for keyword creation.

I still don't think we should highlight that token.

**Comment by Malabarba** [comment]
I see your point. In terms of logic I'm kinda neutral on it now. 

In terms of convenience, I still prefer the current mode. Changing the color of the : would add visual clutter without highlighting anything useful. (in fact, that's one of the reasons I don't like what we did with the / either, but I was out-voted ☺)

For instance,giving the alias a different colour actually highlights the alias (which is relevant information), but giving the : a different color isn't highlighting anything useful. 

In any case, I'm not gonna start bike shedding here. 😜
That's my vote because I don't think the added visual clutter is worth it.

**Comment by Malabarba** [comment]
One bit of visual clutter I would consider useful is to colorize the second : in `::hi` as an alias. Right now these look a lot like regular keywords, so it might be good to differentiate them.

**Comment by bbatsov** [comment]
> One bit of visual clutter I would consider useful is to colorize the second : in ::hi as an alias. Right now these look a lot like regular keywords, so it might be good to differentiate them.

Yeah, that's reasonable.

**Comment by expez** [comment]
> One bit of visual clutter I would consider useful is to colorize the second : in `::hi` as an alias. Right now these look a lot like regular keywords, so it might be good to differentiate them.

I think we should do both.  I feel I made a pretty compelling case that keywords are different in clojure than they are in elisp or common lisp and we shouldn't just inherit the font-locking because it's convenient.

**Comment by bbatsov** [comment]
> I feel I made a pretty compelling case that keywords are different in clojure than they are in elisp or common lisp and we shouldn't just inherit the font-locking because it's convenient.

I'll think about it, but right now I'm still not convinced the change makes a lot of sense.

**Comment by Malabarba** [comment]
>  I feel I made a pretty compelling case that keywords are different in clojure than they are in elisp or common lisp

You did, and you convinced me.
I'm just saying that making this change would add visual clutter without achieving anything.

**Comment by expez** [comment]
> I'm just saying that making this change would add visual clutter without achieving anything.

Well, I think we should do what you suggested, even if it increases clutter.  Here are the two cases for a symbol like `::foo`.

1. No face - alias face - keyword face
2. Keyword face - alias face - keyword face

For regular namespaced symbols, like `:foo/bar` we get:

1. No face - alias face - no face - keyword face
2. keyword face - alias face - no face - keyword face

I'm interpreting clutter as 'transition between faces' and by that definition there is an equal amount of clutter.

**Comment by Malabarba** [comment]
Then there are the two cases for a regular keyword `:foo`:

1. No face - keyword face
2. Keyword face - keyword face

In this case (which is the most common) we would be adding clutter.
