### ISSUE TITLE
Semantic indentation?

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/clojure-mode#398]
I recently came across a description of [semantic indentation for SLIME](https://common-lisp.net/project/slime/doc/html/Semantic-indentation.html), which sounds pretty sweet.

Is it possible to implement this for Clojure through CIDER, instead of having to specify indentation for special forms and macros with `define-clojure-indent`?

**Comment by bbatsov** [comment]
This is doable, but I'm not sure how useful it will be. There was a ticket about this for CIDER a while back, but I think I closed it when we added support for indentation metadata. Guessing the indentation from some param names simply doesn't feel very reliable to me. But in general implementing this should be rather simple - when you evaluate some macro, we'd inspect its params and add some indentation metadata automatically if we find some "special" param names.

**Comment by Malabarba** [comment]
I implemented something like that when I was implementing the indentation metadata. In the end, I pulled it out because it just wasn't reliable. 

1. People are (sadly) not that careful in Clojure when naming their arguments. 
2. Multi-arity is a problem. If the macro has two arities, which one do you use when indenting? 
3. It doesn't support a lot of macros from core whose internal complexity is not reflected on the arglist (for instance, the whole defrecord family).

**Comment by xiongtx** [comment]
:+1: Great that it's been considered! Yes, the `defrecord` family is *weird*. I'll close this then.
