### ISSUE TITLE
Indentation bug involving strings 

### ISSUE THREAD

**Issue by sooheon** [clojure-emacs/clojure-mode#405]
## Expected behavior

Given the following with cursor at `|`:

```
(def foo |"abc")
```

`indent-for-tab-command` should make no change. The sexp is already correctly indented.
## Actual behavior

```
  (def foo |"abc")
```

Sexp is indented two spaces.
## Steps to reproduce the problem

The above case. When the string is on the next line, it is not reproduced.
### clojure-mode version information

```
clojure-mode (version 5.5.2)
```
### Emacs version

Emacs 25.1.1
### Operating system

OS X El Cap

**Comment by Malabarba** [comment]
Verified.

**Comment by drewverlee** [comment]
This happens for me on Ubuntu with spacemacs. Not sure what other information would be helpful.

**Comment by codeasone** [comment]
I'm having a similar issue: 

```
GNU Emacs 26.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-01-26
clojure-mode (version 5.7.0-snapshot)
Version: 20180202.922
Commit: 5cf0fd9360dc5a9a95464601319062673d213807
```

With the following `var` definition: 
```
(def foo "|abc")
``` 
And cursor at `|` 

Entering any character causes unhelpful (and annoying) indentation:

```
  (def foo "Mabc")
``` 

It appears to be because `clojure-mode` determines that the form is a [docstring](https://github.com/clojure-emacs/clojure-mode/blob/5cf0fd9360dc5a9a95464601319062673d213807/clojure-mode.el#L1207)

Unfortunately I don't have the time to debug the treatment of [syntax-ppss](https://www.gnu.org/software/emacs/manual/html_node/elisp/Position-Parse.html), which I suspect is at the root of the issue.

**Comment by cichli** [comment]
Thanks for the report.
