### ISSUE TITLE
Migrate the tests to buttercup

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clojure-mode#422]
`ert` is horrible and we're already using https://github.com/jorgenschaefer/emacs-buttercup for CIDER's test suite. Ideally we should use buttercup here as well. 

The transition should be relatively simple, but it will obviously require some manual work.

@cskksc you tackled this for CIDER, let me know if you'd be willing to help with `clojure-mode` as well.

**Comment by cskksc** [comment]
@bbatsov I'd be happy to :-) Adding this to my TODO list. I'll get started on this soon.

**Comment by bbatsov** [comment]
Thanks!

**Comment by anthonygalea** [comment]
I believe this issue can be closed @bbatsov.

**Comment by tarsius** [comment]
@anthonygalea Could you please change this so that this package does not provide the feature `test-helper`. Another package, `mocha`,  provides this same feature. Neither package should do so.

You might argue that this isn't a library intended for end-users, which is exactly my point: is is not a library. Such non-library emacs-lisp files should not provide a feature because the `require`/`provide` machinery is intended for things that are to be loaded for the benefit of end-users.

Test utilities however can be loaded using `load` or `load-file`. The location of such helpers is known, relative to the main testing entry point.

So the best approach would be to do the things necessary to be able to remove the `provide` form (what that involves can differ from case to case and I didn't look at the details in this case). Alternatively you could rename the file to `clojure-mode-test-helpers.el` and adjust the feature accordingly.

----

I detected this issue as part of my work on the [Emacsmirror](https://emacsmirror.net), specifically the "make sure no two packages (out of >7000) provide the same features", which I am doing [very successfully](https://emacsmirror.net/stats/issues.html), but its a constant effort.

**Comment by tarsius** [comment]
More information about this particular feature and how so many packages ended up providing it can be found at https://github.com/rejeep/ert-runner.el/issues/38.

**Comment by tarsius** [comment]
The issue for the other package currently providing this feature is https://github.com/scottaj/mocha.el/issues/62.

**Comment by bbatsov** [comment]
> Test utilities however can be loaded using load or load-file. The location of such helpers is known, relative to the main testing entry point.

Good point! 

So the best approach would be to do the things necessary to be able to remove the provide form (what that involves can differ from case to case and I didn't look at the details in this case). Alternatively you could rename the file to clojure-mode-test-helpers.el and adjust the feature accordingly.

Yeah, I guess the rename is a good option as well and it requires a bit less work.

**Comment by anthonygalea** [comment]
> Such non-library emacs-lisp files should not provide a feature because the `require`/`provide` machinery is intended for things that are to be loaded for the benefit of end-users.

Thanks for pointing this out @tarsius was not aware.

My original issue was that I needed the code in `test-helper.el` to be loaded before the tests and I thought `provide`/`require` was the correct way to do that. Took a brief look into buttercup and if I understood it correctly it loads test-helper [here](https://github.com/jorgenschaefer/emacs-buttercup/blob/master/buttercup.el#L1283) using `directory-files-recursively`. By moving test-helper to a `utils` folder it ends up being loaded before the tests which solves my original issue without using `provide`/`require`.

**Comment by tarsius** [comment]
Thanks!
