### ISSUE TITLE
Not properly indenting "let" binding sequences

### ISSUE THREAD

**Issue by grkuntzmd** [clojure-emacs/clojure-mode#45]
"let" binding blocks containing complex bindings are not indented properly.

    (let [[x
           y] (range 2)

           [a b] (["foo" "bar"])]
      (print x y a b))

Notice that the line that starts with `[a ...]` is lined up under the `y` in the line above. It should line up under the `[x ...`. It appears to be a problem with having 2 s-expressions on the lines starting `[x ...`

**Comment by mrcslws** [comment]
I'm not sure if "+1"s are useful, but I run into this one all the time. I sometimes work around it by writing ugly code:

~~~clojure
(let [[a b
       c]
      (foo bar)
      d 41])
~~~

instead of the more natural but wrongly indented

~~~clojure
(let [[a b
       c] (foo bar)
       d 41])
~~~

Obviously all of this code looks silly, but it makes sense when you are either:

a. Destructuring lots of values and need to wrap to a new line
b. Avoiding indenting `(foo bar)` way to the right, since it might be a big sexpr, e.g. a `reduce`.

**Comment by bbatsov** [comment]
Patches are way more useful. :-) I have a ton of work and fixing this is pretty low on my todo list, so help is welcome.
