### ISSUE TITLE
global-prettify-symbols-mode does not work when symbol squished in between other chars

### ISSUE THREAD

**Issue by avocadoras** [clojure-emacs/clojure-mode#517]
## Expected behavior
`(defun water→ice [] (println "frozen"))`
## Actual behavior
`(defun water->ice [] (println "frozen"))`

## Steps to reproduce the problem
1. `C-x C-f`
2. insert `//`
3. insert  `tmp/test.clj`
4. insert in buffer `(defn water->ice [] (println "frozen"))` `RET` `(defn water -> ice [] (println "frozen"))`

### clojure version

latest but `clojure-mode-display-version` says `clojure-mode (version nil)`

### Emacs version

26.1

### Operating system

macOS Mojave

### relevant setup

```elisp
  (use-package clojure-mode
    :hook (turn-on-eldoc-mode)
    :ensure t)

  (global-prettify-symbols-mode t)
  (defun my-add-pretty-lambda ()
    "Make some word or string show as pretty Unicode symbols"
    (setq prettify-symbols-alist
	  '(
	    ("lambda" . 955) ; λ
	    ("->" . 8594)    ; →
	    ("=>" . 8658)    ; ⇒
	    ("map" . 8614)   ; ↦
	    )))
  (add-hook 'clojure-mode-hook 'my-add-pretty-lambda)
```

**Comment by Malabarba** [comment]
From what I understand, prettify-symbols-mode acts on entire symbols by design, so there's not much we can do unless we implement this feature from scratch. 
Honestly though, doing this might even have relevant performance implications (not to mention it's a lot of work, of course), so I'm not sure it would be a good idea.

**Comment by bbatsov** [comment]
Yeah, I don't think there's much we can do about this.
