### ISSUE TITLE
clojure-in-docstring-p is wrong when string contains backslash (\)

### ISSUE THREAD

**Issue by Frozenlock** [clojure-emacs/clojure-mode#544]
## Expected behavior

```clj
(def test-string
  "this
is
my
string")
```
Highlighted as a normal string.

## Actual behavior

```clj
(def test-string
  "this\n
  is
  my
  string")
```
Automatic indentation (unwanted in a string!) AND highlighted as a docstring.

## Steps to reproduce the problem

Insert an escape character (\\) to see the string switch to a docstring highlighting.

Eval `(clojure-in-docstring-p)` while the cursor is on the string to see that the result is wrong.

### clojure-mode version information

clojure-mode (version 5.11.0)

### Emacs version

Emacs 26.2

### Operating system

Ubuntu 18.04.3 LTS

**Comment by isdanni** [comment]
I'm having the same problem. Same clojure & OS version, Emacs 26.3.

**Comment by kylc** [comment]
I've done some digging and I've narrowed it down to these lines in the `clojure-font-lock-syntactic-face-function` function:

```emacs-lisp
(not (and (string= "def" firstsym)
        (save-excursion
            (goto-char startpos)
            (goto-char (+ startpos (length (sexp-at-point)) 2)) ;; <=====
            (looking-at "[ \r\n\t]*\)"))))
```

`(length (sexp-at-point))` does not return useful value in this context for strings with escape characters in them, e.g.:

```clojure
(length "abc")   ;=> 3
(length "abc\n") ;=> 4
```

In the example string "abc\n", the function needs to move over **5** characters to find the closing parenthesis it's looking for, but instead it only moves over 4, landing on the closing quote, and determining that this is not the last item in the `def` form and is therefore a docstring.

Is there a function that can be used to escape the string or otherwise find its "length including escape characters"? `string-width` nor `string-bytes` seem to be what we're after. Additionally, `bounds-of-thing-at-point` seems to be affected by the same logic error and so can't be used here.
